/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoProtectedApiRouteImport } from './routes/demo/protected-api'
import { Route as DemoKeycloakRouteImport } from './routes/demo/keycloak'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoProtectedApiRoute = DemoProtectedApiRouteImport.update({
  id: '/demo/protected-api',
  path: '/demo/protected-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoKeycloakRoute = DemoKeycloakRouteImport.update({
  id: '/demo/keycloak',
  path: '/demo/keycloak',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/keycloak': typeof DemoKeycloakRoute
  '/demo/protected-api': typeof DemoProtectedApiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/keycloak': typeof DemoKeycloakRoute
  '/demo/protected-api': typeof DemoProtectedApiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/keycloak': typeof DemoKeycloakRoute
  '/demo/protected-api': typeof DemoProtectedApiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/keycloak' | '/demo/protected-api'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/keycloak' | '/demo/protected-api'
  id: '__root__' | '/' | '/demo/keycloak' | '/demo/protected-api'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoKeycloakRoute: typeof DemoKeycloakRoute
  DemoProtectedApiRoute: typeof DemoProtectedApiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/protected-api': {
      id: '/demo/protected-api'
      path: '/demo/protected-api'
      fullPath: '/demo/protected-api'
      preLoaderRoute: typeof DemoProtectedApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/keycloak': {
      id: '/demo/keycloak'
      path: '/demo/keycloak'
      fullPath: '/demo/keycloak'
      preLoaderRoute: typeof DemoKeycloakRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoKeycloakRoute: DemoKeycloakRoute,
  DemoProtectedApiRoute: DemoProtectedApiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
